version: '3.8'

services:
  frontend:
    build:
      context: ./client  
      dockerfile: Dockerfile  
    ports:
      - "5173:5173"
    environment:
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_TINYMCE_KEY=${VITE_TINYMCE_KEY}
    depends_on:
      - backend

  backend:
    build: 
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
